### ISSUE TITLE
Error building Sphinx documentation

### ISSUE THREAD

**Issue by pedro-w** [dylan-lang/opendylan#1069]
Attempting to build the docs gives me errors, for example the library reference (CWD is `~/opendylan/documentation/library-reference`)
```
$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.7.2

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/home/p/.local/lib/python2.7/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/home/p/.local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/p/.local/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 21, in <module>
    import sphinxcontrib.dylan.themes as dylan_themes
ImportError: No module named dylan.themes

Makefile:45: recipe for target 'html' failed
make: *** [html] Error 2
```
Using python 2.7.12 from Ubuntu and Sphinx 1.7.2 installed with pip.

This seems to be because Python has already imported a package called `sphinxcontrib` and therefore does not import the one in `opendylan/documentation/sphinx-extensions`

**Comment by pedro-w** [comment]
Possible fix is:
```
diff --git a/documentation/library-reference/source/conf.py b/documentation/library-reference/source/conf.py
index 117a1b8..a9f67e7 100644
--- a/documentation/library-reference/source/conf.py
+++ b/documentation/library-reference/source/conf.py
@@ -16,9 +16,9 @@ import sys, os
 # If extensions (or modules to document with autodoc) are in another directory,
 # add these directories to sys.path here. If the directory is relative to the
 # documentation root, use os.path.abspath to make it absolute, like shown here.
-sys.path.insert(0, os.path.abspath('../../sphinx-extensions'))
+sys.path.insert(0, os.path.abspath('../../sphinx-extensions/sphinxcontrib'))
 
-import sphinxcontrib.dylan.themes as dylan_themes
+import dylan.themes as dylan_themes
 
 # -- General configuration -----------------------------------------------------
 
@@ -27,7 +27,7 @@ import sphinxcontrib.dylan.themes as dylan_themes
 
 # Add any Sphinx extension module names here, as strings. They can be extensions
 # coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
-extensions = ['sphinxcontrib.dylan.domain']
+extensions = ['dylan.domain']
 
 # Add any paths that contain templates here, relative to this directory.
 templates_path = ['_templates']
```
This would need to be repeated in all the documentation subdirs.
(Not a Python/Sphinx expert so not sure if this is the right way to do it)

**Comment by cgay** [comment]
pedro-w, can this be closed now?

**Comment by pedro-w** [comment]
It fixed the problem I was seeing on my system, so as far as I know it can be closed.
Thanks for your help.
