### ISSUE TITLE
Porting to new Platform (FreeBSD PowerPC64)

### ISSUE THREAD

**Issue by lenoil98** [dylan-lang/opendylan#1643]
’m attempting to port to PowerPC64 on FreeBSD.  I’m somewhat using the porting instructions and have made all necessary changes.  I’ve been successful in almost getting things to work building from the host computer.  Things seem to work building the hello-world or compiler, until it gets to linking the executable.  Below is what is printed when it stops.  Not sure what these “undefined Jam rules" means.

Optimizing library dylan-compiler
Generating code for library dylan-compiler
Linking object files for library dylan-compiler
Saving database for library dylan-compiler
Build of 'dylan-compiler' completed
Linking dylan-compiler
Invoking undefined Jam rule DylanLibrary
Invoking undefined Jam rule DylanLibraryFiles
Invoking undefined Jam rule DylanLibraryBaseAddress
Invoking undefined Jam rule DylanLibraryCHeaders
Invoking undefined Jam rule DylanLibraryRCFiles
Invoking undefined Jam rule DylanLibraryUses
Invoking undefined Jam rule DylanLibraryUses
Invoking undefined Jam rule DylanLibraryUses
Invoking undefined Jam rule DylanLibraryUses
Invoking undefined Jam rule DylanLibraryUses
Invoking undefined Jam rule DylanLibraryUses
Invoking undefined Jam rule DylanLibraryUses
Invoking undefined Jam rule DylanLibraryUses
Invoking undefined Jam rule DylanLibraryUses
Invoking undefined Jam rule DylanLibraryUses
Invoking undefined Jam rule DylanLibraryUses
Invoking undefined Jam rule DylanLibraryUses

Internal error: Link failed: don't know how to build exe
Exiting with return code -1

All compiled files and libraries are deleted.  Only the converted "c" files and build log are left. 

Any help will be greatly appreciated.

Thanks in advance!

**Comment by cgay** [comment]
Hi, this isn't my are of expertise but here are two pointers that may help until @housel gets a chance to chime in.

* [Jam-based Build System](https://opendylan.org/hacker-guide/build-system.html)
* [Jam files for other platforms](https://github.com/dylan-lang/opendylan/tree/master/sources/jamfiles

**Comment by housel** [comment]
Yes, you need to have a Jam build script for your platform. Most of the per-platform build scripts are pretty similar; the important thing its the `include` at the end of `posix-build.jam`; this is the reason most of the listed rules were undefined.

**Comment by lenoil98** [comment]
I solved my issue.  A ‘space’ was missing before a semicolon on a line in my build script.  Everything builds now.

Now I have to debug why hello-world segfaults.

**Comment by lenoil98** [comment]
I've tried debugging, but have hit a brick wall.  Any suggestions?

Here's what I get using gdb:
@blackbird-powerpc64:~/Devel/opendylan-2020.1.0/_build/bin # gdb hello-world
GNU gdb (GDB) 14.1 [GDB v14.1 for FreeBSD]
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "powerpc64-portbld-freebsd14.1".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from hello-world...
Reading symbols from /root/Devel/opendylan-2020.1.0/_build/bin/hello-world.dbg...
(gdb) run
Starting program: /root/Devel/opendylan-2020.1.0/_build/bin/hello-world 

Program received signal SIGSEGV, Segmentation fault.
Invalid permissions for mapped object.
0x00000008110121b8 in ?? ()
(gdb) backtrace
#0  0x00000008110121b8 in ?? ()
#1  0x0000000000080100 in ?? ()
Backtrace stopped: Cannot access memory at address 0x8105a294810
(gdb) disass
No function contains program counter for selected frame.
(gdb) quit
A debugging session is active.

	Inferior 1 [process 70501] will be killed.

Quit anyway? (y or n) y

**Comment by lenoil98** [comment]
Okay, digging a little bit deeper, I used dumped the freshly build dylan-compiler and compared it to the compiler on the host.  Below is what I got:

_build/bin/dylan-compiler:	file format elf64-powerpc

DYNAMIC SYMBOL TABLE:
0000000000000000      DF *UND*	0000000000000000 (FBSD_1.7)   0x60 __libc_start1
0000000000000000  w   D  *UND*	0000000000000000              _Jv_RegisterClasses
0000000000000000      DO *UND*	0000000000000000              Tcommand_argumentsT
0000000000000000      DO *UND*	0000000000000000              Tcommand_nameT
0000000000000000      DF *UND*	0000000000000000              0x60 _Init_dylan_compiler_
0000000000000000      DF *UND*	0000000000000000              0x60 primitive_make_vector
0000000000000000      DF *UND*	0000000000000000              0x60 primitive_raw_as_string
0000000010031780 g    DO .data	0000000000000008              __progname
0000000010031790 g    DO .bss	0000000000000008              environ
0000000010011070 g    DF .init	0000000000000000              0x60 _init
00000000100110b0 g    DF .fini	0000000000000000              0x60 _fini
00000000100317c8 g    D  .plt	0000000000000000              end
0000000010011124 g    D  .glink	0000000000000000              etext


/usr/local/lib/opendylan-2020.1/bin/dylan-compiler:	file format elf64-x86-64

DYNAMIC SYMBOL TABLE:
0000000000000000      DF *UND*	0000000000000047 (FBSD_1.0)   atexit
0000000000000000      DO *UND*	0000000000000004              TargcT
0000000000000000      DF *UND*	0000000000000036 (FBSD_1.0)   exit
0000000000000000      DO *UND*	0000000000000008              TargvT
0000000000000000  w   D  *UND*	0000000000000000              _Jv_RegisterClasses
0000000000000000      DF *UND*	0000000000000006 (FBSD_1.0)   _init_tls
0000000000000000      DF *UND*	000000000000005d              _Init_dylan_compiler_
00000000006016c8 g    D  *ABS*	0000000000000000              _end
00000000006016b9 g    D  *ABS*	0000000000000000              _edata
00000000006016c0 g    DO .bss	0000000000000008              environ
00000000006016b9 g    D  *ABS*	0000000000000000              __bss_start
0000000000400e96 g    D  *ABS*	0000000000000000              etext
00000000006016a0 g    DO .data	0000000000000008              __progname
00000000006016c8 g    D  *ABS*	0000000000000000              end

Now sure what's happening, it looks like something is amiss.  Thoughts!

**Comment by housel** [comment]
There's not necessarily anything amiss here; you're probably using the C back-end for ppc64, but the host compiler was compiled with the LLVM back-end, so the `main` program looks a bit different. (Dylan executables don't contain much but a call to initialize the included libraries; the real code is in the shared library rather than the executable.)

When tracing through startup and I don't get useful backtraces in gdb, I normally go the other way, namely: put a breakpoint at main, and single-step (instructions usually) until I see something go wrong. https://opendylan.org/hacker-guide/runtime/startup.html describes what the Dylan startup is supposed to look like.

**Comment by lenoil98** [comment]
I don’t see any information concerning the c-backend.  There’s only descriptions for  LLVM and HARP.  LLVM does not support powerpc.

**Comment by lenoil98** [comment]
It looks like this is a lost cause, so I’m going to close this. Thanks for your help.
