### ISSUE TITLE
element out of range error in reader

### ISSUE THREAD

**Issue by waywardmonkeys** [dylan-lang/opendylan#401]
If you try to compile invalid code like:

``` dylan
  let a = #roil:{abc;
```

You get an error from here:

```
#7  0x00046281 in Kelement_range_errorVKeI ()
#8  0x00ddbe79 in Kmake_hash_literalVdfmc_readerMM0I ()
```

**Comment by fraya** [comment]
With version 2023.1pre compiler does not show an error, so this issue should be closed.

```
Open Dylan 2023.1pre
Processing library play-d782189b83c5
...play-d782189b83c5/main.dylan:4.9-10: Serious warning - Invalid token beginning "#" encountered.
              -
      let a = #roil:{abc;
              -
Build of 'play-d782189b83c5' completed
in 2.021981 seconds
```
