### ISSUE TITLE
fbsd64 cross-compiled hello-world crashes

### ISSUE THREAD

**Issue by promovicz** [dylan-lang/opendylan#514]
In a hacked-up cross build I could build a hello-world, but it crashes in thread library init:

```
#0  SLOT_VALUE (object=Cannot access memory at address 0x0
) at /home/jenkins/workspace/opendylan-release-freebsd-x86/sources/lib/run-time/c-run-time.c:3950
#1  0x0000000800ebe747 in Kbootstrap_allocate_repeated_discriminatorYdispatch_engine_internalVdylanI (entry_type_=Cannot access memory at address 0x0
) at new-dispatch.c:9799
#2  0x0000000800ebbe20 in Kmake_initial_class_keyed_discriminatorYdispatch_engine_internalVdylanI (code_=Cannot access memory at address 0x0
) at new-dispatch.c:9346
#3  0x0000000800ebdaba in Kmake_by_singleton_class_discriminatorYdispatch_engine_internalVdylanI (argnum_=dwarf2_read_address: Corrupted DWARF expression.
) at new-dispatch.c:5371
#4  0x0000000800ec19cf in Kcompute_subdiscriminator_for_argYdispatch_engine_internalVdylanI (ds_=dwarf2_read_address: Corrupted DWARF expression.
) at discrimination.c:5037
#5  0x0000000800ec3086 in Kcompute_discriminator_for_argYdispatch_engine_internalVdylanI (argnum_=Cannot access memory at address 0x0
) at discrimination.c:5592
#6  0x0000000800ec046b in Kwalk_existing_dispatch_engineYdispatch_engine_internalVdylanI (ds_=Variable "ds_" is not available.
) at discrimination.c:5158
#7  0x0000000800ec142e in Kcompute_dispatch_from_rootYdispatch_engine_internalVdylanI (ds_=Cannot access memory at address 0x0
) at discrimination.c:1884
#8  0x0000000800ec1229 in Kcompute_dispatch_engineYdispatch_engine_internalVdylanI (ds_=Cannot access memory at address 0x0
) at discrimination.c:8327
#9  0x0000000800eb9649 in Khandle_missed_dispatchVKgI (d_=Cannot access memory at address 0x0
) at new-dispatch.c:14347
#10 0x0000000800f59e5c in general_engine_node_n_engine (a1=Unhandled dwarf expression opcode 0x0
) at /home/jenkins/workspace/opendylan-release-freebsd-x86/sources/lib/run-time/c-run-time.c:2052
#11 0x0000000800ec8636 in _Init_dylan__X_thread_for_user () at thread.c:1159
#12 0x0000000800ea9276 in _Init_dylan_ () at _glue.c:293
#13 0x0000000800f68872 in __do_global_ctors_aux () from /usr/home/jenkins/opendylan-fbsd64/bin/../lib//libdylan.so
#14 0x0000000800ea5d56 in _init () from /usr/home/jenkins/opendylan-fbsd64/bin/../lib//libdylan.so
#15 0x0000000800619560 in ?? ()
#16 0x00000008006066a1 in dlinfo () from /libexec/ld-elf.so.1
#17 0x0000000800609085 in dlsym () from /libexec/ld-elf.so.1
#18 0x0000000800601f89 in .text () from /libexec/ld-elf.so.1
#19 0x0000000000000000 in ?? ()
#20 0x0000000000000000 in ?? ()
#21 0x0000000000000000 in ?? ()
#22 0x0000000000000001 in ?? ()
#23 0x00007fffffffde30 in ?? ()
#24 0x0000000000000000 in ?? ()
#25 0x00007fffffffde51 in ?? ()
#26 0x00007fffffffde5c in ?? ()
#27 0x00007fffffffde73 in ?? ()
#28 0x00007fffffffded2 in ?? ()
#29 0x00007fffffffdedc in ?? ()
#30 0x00007fffffffdef4 in ?? ()
#31 0x00007fffffffdf0a in ?? ()
```

(gdb is printing more such junk lines up until)

```
#640 0x0000000000000000 in ?? ()
#641 0x0000000000000000 in ?? ()
#642 0x0000000000000000 in ?? ()
#643 0x0000000000000000 in ?? ()
#644 0x73752f0000000000 in ?? ()
#645 0x6a2f656d6f682f72 in ?? ()
#646 0x6f2f736e696b6e65 in ?? ()
#647 0x6e616c79646e6570 in ?? ()
#648 0x2f3436647362662d in ?? ()
#649 0x6c6c65682f6e6962 in ?? ()
#650 0x00646c726f772d6f in ?? ()
#651 0x00007fffffffdc40 in ?? ()
#652 0x0000000000000001 in ?? ()
#653 0x00007fffffffdc50 in ?? ()
#654 0x000000000000000b in ?? ()
Cannot access memory at address 0x7ffffffff000
```

**Comment by housel** [comment]
Everything is working for me at this point on x86_64 FreeBSD 12.0
